package com.edinarobotics.utils.autonomous;

/**
 * This interface represents an object that can be used to get a String
 * value at runtime.
 */
public interface StringSource {
    
    /**
     * Gets the {@link String} value generated by this StringSource.
     * @return The {@link String} value generated by this StringSource.
     */
    public String getString();
}
